# Netlify konfigurace

[build]
  publish = "src"
  command = ""

# Hezčí URL bez .html
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/v1"
  to = "/v1.html"
  status = 200

[[redirects]]
  from = "/start"
  to = "/start.html"
  status = 200
