/* EvalAI — definice otázek
 *
 * Vychází z docs/design.md sekce 3.
 * Změna struktury otázek MUSÍ jít ruku v ruce s úpravou scoring formule
 * v apps-script/webhook.gs.
 */

window.EVALAI_QUESTIONS = [
  {
    id: 'q1',
    section: 'Zkušenost',
    n: 1,
    title: 'Jak dlouho aktivně používáš AI nástroje?',
    type: 'single',
    options: [
      { value: 'never',  label: 'Vůbec / jen jsem to párkrát zkusil/a' },
      { value: 'lt6m',   label: 'Méně než 6 měsíců' },
      { value: '6m_2y',  label: '6 měsíců až 2 roky' },
      { value: 'gt2y',   label: 'Více než 2 roky' },
    ],
  },
  {
    id: 'q2',
    section: 'Zkušenost',
    n: 2,
    title: 'Jak často AI typicky používáš?',
    type: 'single',
    options: [
      { value: 'never',   label: 'Vůbec / sporadicky' },
      { value: 'monthly', label: 'Občas (párkrát měsíčně)' },
      { value: 'weekly',  label: 'Pravidelně (alespoň týdně)' },
      { value: 'daily',   label: 'Denně' },
      { value: 'always',  label: 'Mnohokrát denně, je součástí mé práce' },
    ],
  },
  {
    id: 'q3',
    section: 'Zkušenost',
    n: 3,
    title: 'Které AI nástroje jsi za poslední měsíc reálně použil/a?',
    subtitle: 'Můžeš zaškrtnout více možností.',
    type: 'multi',
    options: [
      { value: 'chatgpt',    label: 'ChatGPT' },
      { value: 'claude',     label: 'Claude' },
      { value: 'gemini',     label: 'Gemini' },
      { value: 'copilot',    label: 'Microsoft Copilot' },
      { value: 'perplexity', label: 'Perplexity' },
      { value: 'notebooklm', label: 'NotebookLM' },
      { value: 'image',      label: 'MidJourney / DALL-E / Sora / Veo' },
      { value: 'audio',      label: 'ElevenLabs / Suno' },
      { value: 'video',      label: 'HeyGen / Synthesia' },
      { value: 'internal',   label: 'Vlastní AI nástroj v práci' },
      { value: 'none',       label: 'Žádný', exclusive: true },
    ],
  },
  {
    id: 'q4',
    section: 'Zkušenost',
    n: 4,
    title: 'Platíš za některou AI službu?',
    type: 'single',
    options: [
      { value: 'no',    label: 'Ne' },
      { value: 'one',   label: 'Ano, jeden placený nástroj' },
      { value: 'multi', label: 'Ano, dva a více' },
    ],
  },
  {
    id: 'q5',
    section: 'Zkušenost',
    n: 5,
    title: 'Co z následujícího jsi v posledních 6 měsících dělal/a?',
    subtitle: 'Můžeš zaškrtnout více možností.',
    type: 'multi',
    options: [
      { value: 'long_prompt', label: 'Píšu prompty, často komplexní a promyšlené' },
      { value: 'custom_gpt',  label: 'Použil/a custom GPT, Project nebo Gem' },
      { value: 'own_data',    label: 'Nahrál/a AI vlastní data (PDF, dokumenty, audio)' },
      { value: 'automation',  label: 'Postavil/a AI automatizaci nebo agenta' },
      { value: 'api',         label: 'Použil/a AI API přes kód (vibe coding nebo skutečně)' },
      { value: 'none',        label: 'Nic z toho', exclusive: true },
    ],
  },
  {
    id: 'q6',
    section: 'Postoj',
    n: 6,
    title: 'Jak vidíš AI z pohledu příštích 5 let?',
    type: 'scale',
    min: 1,
    max: 5,
    leftLabel: 'Spíš ohrožení',
    rightLabel: 'Velkou příležitost',
  },
  {
    id: 'q7',
    section: 'Postoj',
    n: 7,
    title: 'Když se zeptám AI na něco ze svého oboru, jak kvalitní bývá odpověď?',
    type: 'scale',
    min: 1,
    max: 5,
    leftLabel: 'Často špatná',
    rightLabel: 'Většinou dobrá',
  },
  {
    id: 'q8',
    section: 'Postoj',
    n: 8,
    title: 'Co tě na AI nejvíc znervózňuje?',
    subtitle: 'Vyber max. 3 možnosti — nebo „Nic z toho".',
    type: 'multi',
    maxSelections: 3,
    options: [
      { value: 'hallucinations', label: 'Halucinace / nepravdivé odpovědi' },
      { value: 'jobs',           label: 'Ztráta pracovních míst' },
      { value: 'authenticity',   label: 'Ztráta autenticity a vlastního myšlení' },
      { value: 'dependency',     label: 'Závislost na AI' },
      { value: 'ethics',         label: 'Etika a soukromí dat' },
      { value: 'safety',         label: 'Bezpečnost a zneužití' },
      { value: 'unknown',        label: 'Strach z neznámého — „nevím, co to je"' },
      { value: 'ecology',        label: 'Ekologická zátěž' },
      { value: 'none',           label: 'Nic z toho — nemám výrazné obavy', exclusive: true },
    ],
  },
  {
    id: 'q9',
    section: 'Postoj',
    n: 9,
    title: 'Mám pocit, že AI zvládnu osvojit a smysluplně využít.',
    type: 'scale',
    min: 1,
    max: 5,
    leftLabel: 'Určitě ne',
    rightLabel: 'Určitě ano',
  },
  {
    id: 'q10',
    section: 'Přirovnání',
    n: 10,
    title: 'Krátké přirovnání',
    subtitle: 'Tahle otázka je pro nás nejcennější. Napiš první, co tě napadne — důvod je nepovinný.',
    type: 'animal',
    fields: [
      { key: 'animalSelf', label: 'K jakému zvířeti přirovnáš sebe?',  placeholder: 'např. delfín, vlk, kočka',           maxLength: 30 },
      { key: 'reasonSelf', label: 'Proč? (volitelné)',                 placeholder: 'Klidně přeskoč.',                     maxLength: 200, multiline: true, optional: true },
      { key: 'animalAi',   label: 'A k jakému zvířeti přirovnáš AI?',  placeholder: 'např. chobotnice, drak, mraveniště',  maxLength: 30 },
      { key: 'reasonAi',   label: 'Proč? (volitelné)',                 placeholder: 'Klidně přeskoč.',                     maxLength: 200, multiline: true, optional: true },
    ],
  },
];
